### ISSUE TITLE
Beaver Builder Front End Editor Conflict in 2.X

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/mrw-web-design-simple-tinymce#4]
[Reported on WordPress.org.](https://wordpress.org/support/topic/2-0-0-beta-with-block-editor-changes-available-for-testing/#post-12199304)

> Just something i noticed quickly while testing. It conflicts with Beaver Builder loading the front end editor if your using the block editor for posts and BB for pages.

**Comment by patric-boehner** [comment]
For due diligence I've tested that it's not a theme or conflict with another plugin.

Taking a further look I'm getting a "Call to undefined function get_current_screen()," so the issue seems to be with the mrw_mce_buttons_1 function for the classic editor. If I disable that function then things load as expected. Might be conflicting with beaver builders own use of TinyMCE buttons.
