### ISSUE TITLE
"Save draft" button styling cut off

### ISSUE THREAD

**Issue by oldrup** [mrwweb/mrw-web-design-simple-tinymce#75]
Hey!

In my install, the "Safe draft" tertiary "button" is having its left border cut off, maybe due to several extra buttons in that menu.

![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/17141205/739c3167-0c12-42c7-be36-d3a7d13556ae)

Is that something you can reproduce? 

Does a filter exists that disables the custom styling of the "safe draft" button?

Not at all a big issue, for sure, but given the extra attention to detail we are offering our editors, we might as well provide a beautiful solution as well :)

**Comment by mrwweb** [comment]
Funky. I'll have to check that out. Thanks for flagging it. I'll admit I haven't see it.

Can you tell me:

- What admin color scheme are you using?
- What is that "B" icon between the Publish button and the block sidebar toggle button?

Right now, there's no filter for the Save Draft button, but I'll add one in the next version.

**Comment by oldrup** [comment]
Okay it seems to display slightly different on different sites. Not sure this is a MRW Simplified Editor issue at all - the plugin might merely expose the issue with the button border, when showing a background.

- The color scheme was Blue I think. Not sure, to be honest.
- The "B" icon is create by the Blocksy theme. It gives access to additional post settings, like layout etc.

I'll see how this button behaves on different installs and get back to you. 🤗

**Comment by mrwweb** [comment]
@oldrup I'm confident that the button looks right on a clean install of WP, so I'm not surprised to hear you're seeing some inconsistently. This is likely a conflict with a plugin or theme (Blocksy seems like a potential culprit.)

If you could tell me the conflicting plugin/theme, I'd considering reviewing the styles to strengthen them, but I'm not going to guarantee a fix. Since this isn't a bug in the core plugin, I'm going to close this for now. If you can isolate the conflict, feel free to re-open and leave enough information to replicate the issue.
